-- 1. Insert Categories 
INSERT INTO categories (name, description) VALUES 
('Frontend', 'Frontend web development languages and tools.'),
('Backend', 'Server-side programming and scripting languages.'),
('Data Science', 'Languages used for data analysis, math, and AI.'),
('Systems', 'Low-level and systems programming languages.'),
('Legacy & Niche', 'Older, enterprise, or highly specialized languages.');

-- 2. Insert 50+ Programming Language Quizzes
-- Structure: (title, description, category_id, difficulty, duration, passing_score, status, max_attempts)

INSERT INTO quizzes (title, description, category_id, difficulty, duration, passing_score, status, max_attempts) VALUES 
('Mastering Python', 'Test your knowledge of Python syntax, concepts, and best practices.', 2, 'INTERMEDIATE', 15, 70, 'published', 3),
('Mastering JavaScript', 'Test your knowledge of JavaScript syntax, concepts, and best practices.', 1, 'BEGINNER', 10, 60, 'published', 3),
('Mastering TypeScript', 'Test your knowledge of TypeScript syntax, concepts, and best practices.', 1, 'ADVANCED', 20, 80, 'published', 3),
('Mastering Java', 'Test your knowledge of Java syntax, concepts, and best practices.', 2, 'INTERMEDIATE', 15, 70, 'published', 3),
('Mastering C++', 'Test your knowledge of C++ syntax, concepts, and best practices.', 4, 'ADVANCED', 30, 75, 'published', 3),
('Mastering C#', 'Test your knowledge of C# syntax, concepts, and best practices.', 2, 'INTERMEDIATE', 15, 70, 'published', 3),
('Mastering Ruby', 'Test your knowledge of Ruby syntax, concepts, and best practices.', 2, 'BEGINNER', 10, 60, 'published', 3),
('Mastering Go', 'Test your knowledge of Go syntax, concepts, and best practices.', 4, 'INTERMEDIATE', 15, 75, 'published', 3),
('Mastering Rust', 'Test your knowledge of Rust syntax, concepts, and best practices.', 4, 'ADVANCED', 30, 80, 'published', 3),
('Mastering Swift', 'Test your knowledge of Swift syntax, concepts, and best practices.', 1, 'INTERMEDIATE', 15, 70, 'published', 3),
('Mastering Kotlin', 'Test your knowledge of Kotlin syntax, concepts, and best practices.', 1, 'INTERMEDIATE', 15, 70, 'published', 3),
('Mastering PHP', 'Test your knowledge of PHP syntax, concepts, and best practices.', 2, 'BEGINNER', 10, 60, 'published', 3),
('Mastering HTML/CSS', 'Test your knowledge of HTML/CSS syntax, concepts, and best practices.', 1, 'BEGINNER', 10, 60, 'published', 3),
('Mastering SQL', 'Test your knowledge of SQL syntax, concepts, and best practices.', 3, 'INTERMEDIATE', 20, 75, 'published', 3),
('Mastering Bash', 'Test your knowledge of Bash syntax, concepts, and best practices.', 4, 'INTERMEDIATE', 15, 70, 'published', 3),
('Mastering R', 'Test your knowledge of R syntax, concepts, and best practices.', 3, 'ADVANCED', 20, 75, 'published', 3),
('Mastering MATLAB', 'Test your knowledge of MATLAB syntax, concepts, and best practices.', 3, 'ADVANCED', 20, 75, 'published', 3),
('Mastering Perl', 'Test your knowledge of Perl syntax, concepts, and best practices.', 2, 'INTERMEDIATE', 15, 70, 'published', 3),
('Mastering Objective-C', 'Test your knowledge of Objective-C syntax, concepts, and best practices.', 1, 'ADVANCED', 20, 75, 'published', 3),
('Mastering Scala', 'Test your knowledge of Scala syntax, concepts, and best practices.', 2, 'ADVANCED', 20, 80, 'published', 3),
('Mastering Dart', 'Test your knowledge of Dart syntax, concepts, and best practices.', 1, 'INTERMEDIATE', 15, 70, 'published', 3),
('Mastering Lua', 'Test your knowledge of Lua syntax, concepts, and best practices.', 4, 'BEGINNER', 10, 60, 'published', 3),
('Mastering Haskell', 'Test your knowledge of Haskell syntax, concepts, and best practices.', 4, 'ADVANCED', 30, 80, 'published', 3),
('Mastering Elixir', 'Test your knowledge of Elixir syntax, concepts, and best practices.', 2, 'ADVANCED', 20, 75, 'published', 3),
('Mastering Clojure', 'Test your knowledge of Clojure syntax, concepts, and best practices.', 2, 'ADVANCED', 20, 75, 'published', 3),
('Mastering F#', 'Test your knowledge of F# syntax, concepts, and best practices.', 2, 'INTERMEDIATE', 15, 70, 'published', 3),
('Mastering Erlang', 'Test your knowledge of Erlang syntax, concepts, and best practices.', 4, 'ADVANCED', 20, 75, 'published', 3),
('Mastering Cobol', 'Test your knowledge of Cobol syntax, concepts, and best practices.', 5, 'INTERMEDIATE', 15, 70, 'published', 3),
('Mastering Fortran', 'Test your knowledge of Fortran syntax, concepts, and best practices.', 5, 'ADVANCED', 20, 75, 'published', 3),
('Mastering Lisp', 'Test your knowledge of Lisp syntax, concepts, and best practices.', 5, 'ADVANCED', 20, 75, 'published', 3),
('Mastering Prolog', 'Test your knowledge of Prolog syntax, concepts, and best practices.', 5, 'ADVANCED', 20, 75, 'published', 3),
('Mastering Pascal', 'Test your knowledge of Pascal syntax, concepts, and best practices.', 5, 'BEGINNER', 10, 60, 'published', 3),
('Mastering Assembly', 'Test your knowledge of Assembly syntax, concepts, and best practices.', 4, 'ADVANCED', 30, 85, 'published', 3),
('Mastering Visual Basic', 'Test your knowledge of Visual Basic syntax, concepts, and best practices.', 5, 'BEGINNER', 10, 60, 'published', 3),
('Mastering Delphi', 'Test your knowledge of Delphi syntax, concepts, and best practices.', 5, 'INTERMEDIATE', 15, 70, 'published', 3),
('Mastering Ada', 'Test your knowledge of Ada syntax, concepts, and best practices.', 4, 'ADVANCED', 20, 75, 'published', 3),
('Mastering ABAP', 'Test your knowledge of ABAP syntax, concepts, and best practices.', 5, 'ADVANCED', 20, 75, 'published', 3),
('Mastering Groovy', 'Test your knowledge of Groovy syntax, concepts, and best practices.', 2, 'INTERMEDIATE', 15, 70, 'published', 3),
('Mastering Julia', 'Test your knowledge of Julia syntax, concepts, and best practices.', 3, 'ADVANCED', 20, 75, 'published', 3),
('Mastering VHDL', 'Test your knowledge of VHDL syntax, concepts, and best practices.', 4, 'ADVANCED', 30, 80, 'published', 3),
('Mastering Verilog', 'Test your knowledge of Verilog syntax, concepts, and best practices.', 4, 'ADVANCED', 30, 80, 'published', 3),
('Mastering Solidity', 'Test your knowledge of Solidity syntax, concepts, and best practices.', 2, 'ADVANCED', 20, 75, 'published', 3),
('Mastering GraphQL', 'Test your knowledge of GraphQL syntax, concepts, and best practices.', 2, 'INTERMEDIATE', 15, 70, 'published', 3),
('Mastering Apex', 'Test your knowledge of Apex syntax, concepts, and best practices.', 5, 'INTERMEDIATE', 15, 70, 'published', 3),
('Mastering VBA', 'Test your knowledge of VBA syntax, concepts, and best practices.', 5, 'BEGINNER', 10, 60, 'published', 3),
('Mastering PowerShell', 'Test your knowledge of PowerShell syntax, concepts, and best practices.', 4, 'INTERMEDIATE', 15, 70, 'published', 3),
('Mastering Awk', 'Test your knowledge of Awk syntax, concepts, and best practices.', 4, 'BEGINNER', 10, 60, 'published', 3),
('Mastering Tcl', 'Test your knowledge of Tcl syntax, concepts, and best practices.', 5, 'INTERMEDIATE', 15, 70, 'published', 3),
('Mastering Scheme', 'Test your knowledge of Scheme syntax, concepts, and best practices.', 5, 'ADVANCED', 20, 75, 'published', 3),
('Mastering WebAssembly', 'Test your knowledge of WebAssembly syntax, concepts, and best practices.', 1, 'ADVANCED', 30, 80, 'published', 3),
('Mastering Scratch', 'Test your knowledge of Scratch syntax, concepts, and best practices.', 1, 'BEGINNER', 10, 50, 'published', 3);